savePrefix: ""
autoInstallPeers: false
strictPeerDependencies: true
overrides:
  vinxi: "$vinxi"
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
onlyBuiltDependencies:
  - better-sqlite3
  - workerd
