// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "preview";
	SENTRY_DSN: "https://2b1a34ea5d3b701283cff3dcbcf79da2@o931378.ingest.us.sentry.io/4508192894943232";
	JWT_ISSUER: "https://phi-ag.cloudflareaccess.com";
	JWT_AUDIENCE: "2858cbaf26a4b2a7f619f5d28ebf2378b97bef58f330c65c1d903b95697a95ba";
	E2E_CLIENT_ID: "ac524ec30129d7a7e941faf6ed54f19c.access";
	R2: R2Bucket;
	DB: D1Database;
	AI: Ai;
	CF_VERSION_METADATA: { id: string; tag: string };
}
