name: e2e

runs:
  using: composite
  steps:
    - name: End-to-End
      uses: phi-ag/run-playwright@e2545afe0352419a2974e7c2a70cdf8a9dd5f85a # v1
      with:
        version: v1.58.2-noble@sha256:6446946a1d9fd62d9ae501312a2d76a43ee688542b21622056a372959b65d63d
        options: -v ${STORE_PATH}:${STORE_PATH}
        run: |
          npm install -g --force corepack
          corepack enable
          corepack prepare --activate

          pnpm config set store-dir ${STORE_PATH}
          pnpm install --frozen-lockfile

          echo Target ${BASE_URL:-localhost}
          pnpm test:e2e
